language: node_js
node_js:
- '8'
install:
- npm ci
script:
- npm test
deploy:
  provider: npm
  email: igor@sowinski.blue
  on:
    branch: master
  skip_cleanup: true
  api_key:
    secure: DAN9NN64khM9A0ZAYcppp9Z4Vq0S5cpC7mtzeBIe/MMSyu4MSP1ZOwHYL29LpjUhVAiUmc3fOA8dVSsCkmD5ggA+3sepbTZr5ENso0/QT3dc4JkKEChoph6iQz9UBNKmcdrhAajNlyB6BdIZUGv+VJ1+aYVDYlOX6yzgv8unwHsue39bZK8BsoaXr0A14xVo817KTZETcaGNk+hPKNgbiIFIBAsRJV91gBsOsLOScgRkaTrsaXpBuGbaaRcW5MJkW+6y+Lb2TWZ+KdYWUpb6XzKpaxntsL/hvTf30suVPsSGFHxwCbFNABMkwlK45NxA5DCDQ/6+oBijR743FgRx3o+i4ic6oT8pWNlY1TP0u295N9lsrgwZ02WdqwH7ztsHnp1EFII9Z2gB/hyQp/L7wNdDDcFBUfE126+T6PhrXOub942SexQe995AaIgw15momHshfVvh8MpOUZTmiQUfSJm3yOphFIdHHEFIpZ6s7H+QExlS+rZaR7WBbJxCfnxB2/y6IUvYumoSxkWuAMnqiegbs0bmlJzzRUCeHvPaoF0vDT8dKADGW2MVIBKpXJLwgTsPUSVhsfNdNRshpC0ITOtdKUvn/9/5CJq4BvlvT5nRDmiMqdztXvMU11lhsIKa7Utpqr7ADhOgoAtGcCLNzrhMaYuVVrrwoL24I8dA1FI=
