language: node_js
node_js:
- '8'
install:
- npm i
script:
- npm run build
- npm test
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  on:
    branch: master
  skip_cleanup: true
  api_key:
    secure: BVBESKq+qJqQ+Ka3BEU/LIqqKB3WbjpT+iwTlsp6FrpKF+UbcJS03fieolpsYqn4QfT0uccfDUJNU6+UuZ4jjcowJBeWhA0u3Lj3HoGwFVe472RztH2fROVsJYdbQyVlGJExnTDNf3PNgw5XcExTZJnWM8WHEV6wutyke98wNAi+PCPoXDUKeJqJyASDk2FdIThCZz2kHW4JlEgy/ql85jLKJaiDbK3q3VExhjrGETIgZA1pQI9NtYpJWcgRYBipyRhKuzT6Yg66G4nJdI9n1OXhilQP4cY8nxoXE065MxA0aZwIW9su3eGVWxCB6dvJtY4RjutXmd/RlbmZEEn0JijvJ94aRnZrGo7Ooi4UU8DXwZdDBh/aueK96SExIGuRIu5cdlprMD4ozL36HC8EEHoIdCbnzWqwdiMhc/pkHSo83e0NkK8jfFPKOqKJ5spIc4U5huAkznlsH1m1USIpVujRqU8M0fNtR+2KXKoVlxiVNG+ZM7TlKmC0KttqtOnjOlN2jTMbgBPLycY4uLYbtsU9/Nx9DtUrz9BXOZgrmBl1lmDw0ndkT1xNFXrVKohhhEBN8qQVP4WmBWg+pD4iXolQjtUKdksCdegKiGHppc3Y9TgdK5XzIywfnWKKahhu2bXzxJXcLprkQNuJGmtAh7u4eScvwnOSYyMNmFLVm8A=
