language: node_js
node_js:
- '8'
install:
- npm i
script:
- npm test
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  on:
    branch: master
  skip_cleanup: true
  api_key:
    secure: U06AzCM0X+WpPgLoR/Ngr572P9p6nIkvR/5GJXqUBsOnSyGCkmIcjZH9PrDmJb87oVmPWQGrJGa+ivoILTbx2usKrqXzIvOd3enxkQUjCjTiLf7ZkwTNspcFbqKPkF7S1sKTzZF+C8e325zocJUuhlMXnXRth7TrRUKQbgguX99+sBudmF2KLFPI/Y+1D8z/Trip5ab42XhiDZISxHBEqRq+H78nQa6wJzjlQlK/g9DeVlLkD/128VfWrKFDInnpiAetxrgaytgdLLGwOMo/ugY2Xnoess1cVLbFGDLt5eXj7MXfRhAVJBylboX7I4dB0JfPho6uZzkc1eXvaAHkIl3LZ41aSoJGKL5Sj2/6MtbyRiLkD2vfFceQzRJvr0xRQ7LTxYMfXKi/rn8GHIWzjMLI60v5nwgktE6hqGjKND1rdo4nxPCBjQ9kU8bExYYEbfGlf4AqyLe8vKNFqgTUChoCzAIwZnsYHeHuPn7Aug3JiWUJoYyhWhIsxL6Hly/NwQbQMhOGEEfw+QwKNgYf2SuzOHaUin/QJvO9JNJ1BCyOoR2xrak3SDBk/RIH6zq6o2gsWa1Ax3CiO36kWPiOzArVWInUszkAOC+uXwksXYWIOi1moXjglCW8ZMsUNszpKBBBMNMgGaDrRE6e4MxYSjiZn5557BqCV31/xaLL3pw=
