language: node_js
node_js:
- '8'
install:
- npm i
script:
- npm run build
- npm test
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  on:
    branch: master
  skip_cleanup: true
  api_key:
    secure: d1nJnitvzPAGvBGdY64JJmhRkV6OvJO0KquM/U75qzasPD5XCIqzpbleHXkoFfdn/Xpp3W3VAcujzMmL+qrCm54NEIgSraTf6SJ8WYDsMPG5rYGgKP/dEhFT2TJhMRt6dIa6rEm9ViqXtMzDnZFqtoUSdbgKswr3ZrT2ioxhuSq96w+U36eWX/QtGDod28aR26wiYWcK05khjKpCpkoTybMfTVzyAnNYRhhN49ZGCm8d2o1JMU77KC1l2+IglrERJaATdqbwQmNZNB8yVg/dZIz61XLYQgukjrkOOIXLtYlpbawIGetJuXu7JohU4kD4rDqE6iwOLhqjWv+Ye04SkjaE5dOAaOBoaDwB8wj/50kmqAUWcIPjpdNo3OkcMeemYd1YyvyVrDd4XtI/WlkxmDC6LbycHxAzEF3qhMzokO1R9CcO2AtDZ6JfQ8TUensF8aYdmYBUaAdOeRrnmU8h2I6Tl8NcrF0XQ5LG50FOGTgyMZOxNAgRviTL2L1PSrau75La8XFG9Q0N5mH4hEpRO15pLOakZ2DYUaBeYKvc30AGPzBCKxdrIFcE32ZiEKN7IaEPXqwxjPap/sFDK5vhpvjBz9JDQ5rDNrJg/3p7IntTeXEx2WPGmfuhJgivDNPNJIywOiSAZH5//NZ1CvmBmVvoE+HHe71oHGEuJ16Z0cY=
