language: node_js
node_js:
- '8'
install:
- npm i
script:
- npm run build
- npm test
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  on:
    branch: master
  skip_cleanup: true
  api_key:
    secure: XkMY5e0dSEu+97sFG4SeYwAWnQ5SEf3aRVmuST3Ec5CLXCwwRKIGNqUV9V/XIY1T0ySNRuRjy0bjmGBfuL7essVoVdm1HIb9M9v/hJwyCRFAT7y+nKSwV2BM2MPXBbNInQaHkLM/yE5/PUjn/HQAL+lQon4DEOgPzGso+9akn5Izoq9I/536LeizNuy4AZPe65O57zNTVSO59p44UxXswUs9TYItF9w0BWdvpQ6cuOu0djTgejwjIw0eTIDuKObz5QeeHVg/RRMJccBbMdiRkCPiHOGUZrv9GcxLYZDqW3feDnd1MRwVkkZMIGUfPwj9wt7VLmgef5G1x4EzX3k27AQ3nK8FxEXE4MaxlsPA3KXIW6w1pvcuYNdQL3OGCBktgzqLwvfF5fxkCke5NRQq9rUdTlmev4aKSn38DCCQntOiApqrXdhgVA98mLaz+Xxu6glkLhghtDk6CYlu4y/unqBsIft12RM4Odh8Q2ynCgb/dXH5kr8kUhf9W2qrip0Hpbr4Fqlq+m/mifqadb9lSl+NrLEwUHL+zNQ3XzODV+e+Li63CE0SAX9sXhNcltFvj4EafDz1+6QfOILzzldb42PLQD+6Whu7Xs4UAxYVs7a9QLjjg6712TWQkbeEEDJEftrqKCRpzL2SYM1h8asSqn3nnrbbO4ykw0SNlaIo3RY=

